"""initial schema

Revision ID: 23ef8b6743ad
Revises: 
Create Date: 2026-05-18 09:15:52.574347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ef8b6743ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='RUB', nullable=False),
    sa.Column('initial_balance_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'RUB'", name='accounts_currency_chk'),
    sa.CheckConstraint("type IN ('card','cash','savings','debt','credit')", name='accounts_type_chk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('accounts_user_active_idx', 'accounts', ['user_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_index('accounts_user_name_uq', 'accounts', ['user_id', 'name'], unique=True, postgresql_where='archived_at IS NULL')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('expense','income','both')", name='categories_kind_chk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # categories_user_name_uq — partial unique с COALESCE(user_id, 0). Expression
    # indexes autogenerate не пишет (Alembic issue #750); делаем руками. COALESCE
    # сводит все системные строки (user_id IS NULL) в один namespace — иначе
    # NULL != NULL и обычный UNIQUE их пропустит.
    op.execute(
        "CREATE UNIQUE INDEX categories_user_name_uq "
        "ON categories (COALESCE(user_id, 0), name) "
        "WHERE archived_at IS NULL"
    )
    op.create_table('receipts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default='uploaded', nullable=False),
    sa.Column('parsed_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('parsed_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('parsed_merchant', sa.Text(), nullable=True),
    sa.Column('parsed_occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("parsed_currency IS NULL OR parsed_currency = 'RUB'", name='receipts_parsed_currency_chk'),
    sa.CheckConstraint("status IN ('uploaded','parsing','parsed','failed','rejected')", name='receipts_status_chk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('receipts_processing_idx', 'receipts', ['status'], unique=False, postgresql_where="status IN ('uploaded','parsing')")
    op.create_index('receipts_user_created_idx', 'receipts', ['user_id', 'created_at'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='RUB', nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'RUB'", name='budgets_currency_chk'),
    sa.CheckConstraint("period IN ('week','month','year')", name='budgets_period_chk'),
    sa.CheckConstraint('ends_on IS NULL OR ends_on > starts_on', name='budgets_dates_chk'),
    sa.CheckConstraint('limit_minor > 0', name='budgets_limit_chk'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('budgets_active_uq', 'budgets', ['user_id', 'category_id', 'period'], unique=True, postgresql_where='archived_at IS NULL')
    op.create_table('goals',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='RUB', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'RUB'", name='goals_currency_chk'),
    sa.CheckConstraint('target_amount_minor > 0', name='goals_target_chk'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('goals_user_active_idx', 'goals', ['user_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='RUB', nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (kind='expense'    AND from_account_id IS NOT NULL AND to_account_id IS NULL     AND category_id IS NOT NULL) OR\n            (kind='income'     AND from_account_id IS NULL     AND to_account_id IS NOT NULL AND category_id IS NOT NULL) OR\n            (kind='transfer'   AND from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND from_account_id <> to_account_id AND category_id IS NULL) OR\n            (kind='adjustment'\n               AND ( (from_account_id IS NOT NULL AND to_account_id IS NULL)\n                  OR (from_account_id IS NULL     AND to_account_id IS NOT NULL) )\n               AND category_id IS NOT NULL)\n            ", name='transactions_kind_fields_chk'),
    sa.CheckConstraint("currency = 'RUB'", name='transactions_currency_chk'),
    sa.CheckConstraint("kind IN ('expense','income','transfer','adjustment')", name='transactions_kind_chk'),
    sa.CheckConstraint('amount_minor > 0', name='transactions_amount_chk'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('transactions_from_acc_idx', 'transactions', ['from_account_id'], unique=False, postgresql_where='from_account_id IS NOT NULL')
    op.create_index('transactions_receipt_idx', 'transactions', ['receipt_id'], unique=False, postgresql_where='receipt_id IS NOT NULL')
    op.create_index('transactions_to_acc_idx', 'transactions', ['to_account_id'], unique=False, postgresql_where='to_account_id IS NOT NULL')
    # DESC порядок на occurred_at — список транзакций «новые сверху» сканит индекс
    # без отдельной sort step. SQLAlchemy declarative не имеет лаконичного способа
    # выразить DESC в Index() — пишем через op.execute.
    op.execute(
        "CREATE INDEX transactions_user_occurred_idx "
        "ON transactions (user_id, occurred_at DESC)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS transactions_user_occurred_idx")
    op.drop_index('transactions_to_acc_idx', table_name='transactions', postgresql_where='to_account_id IS NOT NULL')
    op.drop_index('transactions_receipt_idx', table_name='transactions', postgresql_where='receipt_id IS NOT NULL')
    op.drop_index('transactions_from_acc_idx', table_name='transactions', postgresql_where='from_account_id IS NOT NULL')
    op.drop_table('transactions')
    op.drop_index('goals_user_active_idx', table_name='goals', postgresql_where='archived_at IS NULL')
    op.drop_table('goals')
    op.drop_index('budgets_active_uq', table_name='budgets', postgresql_where='archived_at IS NULL')
    op.drop_table('budgets')
    op.drop_index('receipts_user_created_idx', table_name='receipts')
    op.drop_index('receipts_processing_idx', table_name='receipts', postgresql_where="status IN ('uploaded','parsing')")
    op.drop_table('receipts')
    op.execute("DROP INDEX IF EXISTS categories_user_name_uq")
    op.drop_table('categories')
    op.drop_index('accounts_user_name_uq', table_name='accounts', postgresql_where='archived_at IS NULL')
    op.drop_index('accounts_user_active_idx', table_name='accounts', postgresql_where='archived_at IS NULL')
    op.drop_table('accounts')
    op.drop_table('users')
